---
title: "Report"
author: "Eric R. Scott"
date: '2022-07-11'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(targets)
tar_load(data) #load the data
```

## My analysis

I tested for a linear relationship between flipper length and body mass, different intercepts by sex, and different slopes by sex. I repeated this analysis for bill length.

## Results

Response: flipper length

```{r}
#| echo: false
#| output: "asis"
tar_read(flipper_table) |> knitr::kable(digits = 3)
```

Body mass and sex are significant, but not their interaction


Response: bill_length

```{r}
#| echo: false
#| output: "asis"
tar_read(bill_table) |> knitr::kable(digits = 3)
```

Body mass and sex are significant, but not their interaction

```{r}
#| echo: false
ggplot(data, aes(x = body_mass_g, y = bill_length_mm, color = sex)) + 
  geom_point() +
  labs(title = "Bill length")
```

```{r}
#| echo: false
ggplot(data, aes(x = body_mass_g, y = flipper_length_mm, color = sex)) + 
  geom_point() + 
  labs(title = "Flipper length")
```

